name: Run Docker Container with Terraform

on:
  push:
    branches:
      - 'ma**'
    tags:
      - 'v*.*.*'

jobs:
  Terraform:
    runs-on: self-hosted
    steps: 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with: 
          terraform_version: '1.4.0'
          cli_config_credentials_hostname: 'app.terraform.io'
      - name: Export Path
        shell: bash
        run: export PATH="/usr/local/bin:$PATH"
      - name: Check Terraform Version
        shell: bash
        run: |
         pwd
         terraform version
  Docker:
    runs-on: self-hosted
    steps:
      - name: Setup Docker
        uses: actions/setup-docker@v2
        with:
          version: 'latest'
# buildx-version: ''
      - name: Check Docker Version 
        shell: bash
        run: docker -v
  Build:
    needs: [Terraform,Docker]
    runs-on: self-hosted
    steps:
      - name: Chekout Repository
        uses: actions/checkout@v4
      - name: Check Working directory location
        shell: bash
        run: |
         pwd
         ls -la
      - name: Terraform init
        run: terraform init
      - name: Terraform plan
        run: terraform plan
      - name: Terraform Apply Logic
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
