name: Run Docker Container with Terraform

on:
  push:
    branches:
      - 'ma**'
    tags:
      - 'v*.*.*'

jobs:
  Build:
    runs-on: self-hosted
    steps:
      - name: Cleanup build folder
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
      - name: Chekout Repository
        uses: actions/checkout@v4
      - name: Check Working directory location and Prerequisites
        shell: bash
        run: |
         pwd
         ls -la
         terraform version
         docker version
      - name: Terraform init
        run: terraform init
      - name: Terraform plan
        run: terraform plan
      - name: Terraform Apply Logic
        run: terraform apply -auto-approve
