name: Run Docker Container with Terraform

on:
  push:
    branches:
      - 'ma**'
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      container_name:
        description: 'Name of the Docker container'
        required: false
        default: 'webcontainer'

jobs:
  Stop-Nginx-Webserver-Container:
    runs-on: self-hosted
    if: github.event_name == 'workflow_dispatch' # Run only for Manual triggers
    outputs:
      container_status: ${{ steps.check_container.outputs.status }}
    steps:
      - name: Cleanup build folder
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
      - name: Chekout Repository
        uses: actions/checkout@v4
      - name: Check Working directory location and Prerequisites
        shell: bash
        run: |
          pwd
          ls -la
          terraform version
          docker version
      - name: Set container name
        id: set_container_name
        run: |
          CONTAINER_NAME="${{ github.event.inputs.container_name || 'webcontainer' }}"
          echo "CONTAINER_NAME=${CONTAINER_NAME}" >> $GITHUB_ENV
          echo "Container name is set to: ${CONTAINER_NAME}"
      - name: Check Docker Container is exist
        id: check_container
        run: |
          if docker ps --filter "name=${{ env.CONTAINER_NAME }}" --filter "status=running" | grep ${{ env.CONTAINER_NAME }}; then
            echo "status=running" >> $GITHUB_OUTPUT
          else
            echo "status=not_running" >> $GITHUB_OUTPUT
          fi
      - name: Stop Docker Container Running
        if: ${{ steps.check_container.outputs.status == 'running' }}
        run: |
          echo "Stopping the Docker container..."
          docker stop ${{ env.CONTAINER_NAME }} || true
          docker rm ${{ env.CONTAINER_NAME }} || true
      - name: Destroy Existing Terraform Infra
        run: |
          terraform init
          terraform destroy -auto-approve
  Start-Nginx-Webserver-Container:
    runs-on: self-hosted
    if: github.event_name != 'workflow_dispatch' # Run only for automatic triggers
    outputs:
      container_status: ${{ steps.check_container.outputs.status }}
    steps:
      - name: Cleanup build folder
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
      - name: Chekout Repository
        uses: actions/checkout@v4
      - name: Check Working directory location and Prerequisites
        shell: bash
        run: |
          pwd
          ls -la
          terraform version
          docker version
      - name: Terraform init
        run: terraform init
      - name: Terraform plan
        run: terraform plan
      - name: Terraform Apply Logic
        run: terraform apply -auto-approve
