name: Run Docker Container with Terraform

on:
  push:
    branches:
      - 'ma**'
    tags:
      - 'v*.*.*'
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  Build:
    runs-on: self-hosted
    steps:
      - name: Chekout Repository
        uses: actions/checkout@v4
      - name: Check Working directory location and Prerequisites
        shell: bash
        run: |
         pwd
         ls -la
         terraform version
         docker version
      - name: Terraform init
        run: terraform init
      - name: Terraform plan
        run: terraform plan
      - name: Terraform Apply Logic
        run: terraform apply -auto-approve
